version: '3.8'

services:
  nextjs:
    build:
      context: .
      target: production
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
