export const seoSchemas = {
  main: {
    "@context": "https://schema.org",
    "@type": "Organization",
    name: "TOO «VARRO Operating Group»",
    alternateName: [
      "VARRO",
      "varro",
      "varo",
      "VARRO Operating Group",
      "VARRO Group",
      "TOO VARRO",
      "TOO VARRO Operating Group",
      "ТОО VARRO",
      "VARRO LLP",
      "varro llp",
      "llp varro",
      "VARRO ЖШС",
      "варро ЖШС",
      "варо ЖШС",
      "варро жшс",
      "LLP VARRO",
      "тоо варо",
      "тоо варро",
      "ТОО «VARRO»",
      "Варро",
      "Варро груп",
      "Варро Оперейтинг Групп",
      "Варро Казахстан",
      "Varro Aktau",
      "Varro KZ",
      "Varro.kz",
      "varro.kz",
      "varro",
      "varro-company",
      "варо",
      "варроу",
      "вару",
      "vaaro",
      "вааро",
      "ваарро",
      "Варро Мұнайгаз",
      "варро мұнай",
      "варо мұнай",
      "вог",
      "ВОГ",
      "Вог",
      "VOG",
      "vog",
      "varro og",
      "varo og",
    ],
    url: "https://varro.kz",
    logo: "https://varro.kz/images/varro.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "БЦ Зодиак, микрорайон 17, здание 39",
      addressLocality: "Актау",
      addressRegion: "Мангистауская область",
      postalCode: "130000",
      addressCountry: "KZ",
    },
    contactPoint: {
      "@type": "ContactPoint",
      telephone: "+7-7292-201-909",
      contactType: "customer support",
      email: "Varro@btmg.kz",
      availableLanguage: ["ru", "kk", "en"],
      description: "Внутренний номер: 2069",
    },
  },
  about: {
    "@context": "https://schema.org",
    "@type": "AboutPage",
    name: "О компании VARRO Operating Group",
    url: "https://varro.kz/about",
    description:
      "TOO «VARRO Operating Group» — нефтегазовая компания в Мангистау, специализирующаяся на добыче и переработке углеводородов.",
  },
  contact: {
    "@context": "https://schema.org",
    "@type": "ContactPage",
    name: "Контакты VARRO Operating Group",
    url: "https://varro.kz/contact",
    contactOption: "https://varro.kz/contact",
  },
  bgpz: {
    "@context": "https://schema.org",
    "@type": "WebPage",
    name: "БГПЗ — Боранкольский газоперерабатывающий завод",
    url: "https://varro.kz/bgpz",
    description:
      "Боранкольский газоперерабатывающий завод (БГПЗ) — современное производство по переработке газа и сжиженных углеводородов.",
  },
  goals: {
    "@context": "https://schema.org",
    "@type": "WebPage",
    name: "Цели VARRO Operating Group",
    url: "https://varro.kz/goals",
    description:
      "Цели компании: эффективность добычи, инновации, цифровизация, экологичность и устойчивое развитие в нефтегазовом секторе.",
  },
  principles: {
    "@context": "https://schema.org",
    "@type": "WebPage",
    name: "Принципы VARRO Operating Group",
    url: "https://varro.kz/principles",
    description:
      "Ключевые принципы: корпоративная ответственность, безопасность, охрана окружающей среды, передовые технологии и HSE-стандарты.",
  },
};
